import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ToastContainer } from 'react-toastify'

import 'react-toastify/dist/ReactToastify.css'
import '@/styles/index.css'
import CustomThemeProvider from '@/services/custom-theme-provider'
import { ReactQueryProvider } from '@/services/react-query-provider'

import HomeLayout from '@/components/HomeLayout'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Tech Showcase',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <ReactQueryProvider>
          <CustomThemeProvider>
            <HomeLayout>{children}</HomeLayout>
          </CustomThemeProvider>
        </ReactQueryProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
